
#include "MyMonsterSpawner.h"
#include "Components/BoxComponent.h"
#include "Components/SceneComponent.h"
#include "Kismet/GameplayStatics.h"
#include "TimerManager.h"
#include "Engine/World.h"

#include "MyPaperMonster.h"
#include "MyPaperCharacter.h"

AMyMonsterSpawner::AMyMonsterSpawner()
{
    PrimaryActorTick.bCanEverTick = false;

    // ЗчЦЎ
    Root = CreateDefaultSubobject<USceneComponent>(TEXT("Root"));
    RootComponent = Root;

    // ЦЎИЎАХ ЙкНК
    TriggerBox = CreateDefaultSubobject<UBoxComponent>(TEXT("TriggerBox"));
    TriggerBox->SetupAttachment(RootComponent);
    TriggerBox->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
    TriggerBox->SetCollisionObjectType(ECC_WorldDynamic);
    TriggerBox->SetCollisionResponseToAllChannels(ECR_Ignore);
    TriggerBox->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);
    TriggerBox->SetBoxExtent(FVector(100.f, 100.f, 100.f));

    // ПоТЪ / ПРИЅТЪ НКЦљ ЦїРЮЦЎ
    LeftSpawnPoint = CreateDefaultSubobject<USceneComponent>(TEXT("LeftSpawnPoint"));
    LeftSpawnPoint->SetupAttachment(RootComponent);
    LeftSpawnPoint->SetRelativeLocation(FVector(-300.f, 0.f, 0.f));

    RightSpawnPoint = CreateDefaultSubobject<USceneComponent>(TEXT("RightSpawnPoint"));
    RightSpawnPoint->SetupAttachment(RootComponent);
    RightSpawnPoint->SetRelativeLocation(FVector(300.f, 0.f, 0.f));
}

void AMyMonsterSpawner::BeginPlay()
{
    Super::BeginPlay();

    // ЦЎИЎАХ ПРЙіЗІ РЬКЅЦЎ ЙйРЮЕљ
    if (TriggerBox)
    {
        TriggerBox->OnComponentBeginOverlap.AddDynamic(
            this,
            &AMyMonsterSpawner::OnTriggerBegin);
    }

    // ЧУЗЙРЬОю ФГНЬ
    CachedPlayer = Cast<AMyPaperCharacter>(
        UGameplayStatics::GetPlayerPawn(this, 0));
}

void AMyMonsterSpawner::OnTriggerBegin(
    UPrimitiveComponent* OverlappedComp,
    AActor* OtherActor,
    UPrimitiveComponent* OtherComp,
    int32 OtherBodyIndex,
    bool bFromSweep,
    const FHitResult& SweepResult)
{
    // РЬЙЬ Чб Йј НшАэ OneShotРЬИщ ЙЋНУ
    if (bOneShot && bHasSpawned)
    {
        return;
    }

    if (!OtherActor || OtherActor != CachedPlayer)
    {
        return;
    }

    bHasSpawned = true;

    // ЗЃД§ ЙцЧт АсСЄ
    bSpawnFromLeft = FMath::RandBool();

    USceneComponent* SpawnPoint = bSpawnFromLeft ? LeftSpawnPoint : RightSpawnPoint;
    USoundBase* UseSound = bSpawnFromLeft ? Sound_Left : Sound_Right;

    // СТ/Пь ЛчПюЕх РчЛ§
    if (UseSound && SpawnPoint)
    {
        UGameplayStatics::PlaySoundAtLocation(
            this,
            UseSound,
            SpawnPoint->GetComponentLocation());
    }

    // 1.5УЪ(ЖЧДТ МГСЄЕШ НУАЃ) ШФ ИѓНКХЭ НКЦљ
    if (SpawnDelay > 0.f)
    {
        GetWorldTimerManager().SetTimer(
            TimerHandle_Spawn,
            this,
            &AMyMonsterSpawner::SpawnMonster,
            SpawnDelay,
            false);
    }
    else
    {
        SpawnMonster();
    }

    // ДйНУ ОШ ОВАд ЧЯАэ НЭРИИщ ЦЎИЎАХ ВєБт
    if (bOneShot && TriggerBox)
    {
        TriggerBox->SetGenerateOverlapEvents(false);
    }
}

void AMyMonsterSpawner::SpawnMonster()
{
    if (!MonsterClass || !CachedPlayer)
    {
        return;
    }

    USceneComponent* SpawnPoint = bSpawnFromLeft ? LeftSpawnPoint : RightSpawnPoint;
    if (!SpawnPoint)
    {
        return;
    }

    const FVector Loc = SpawnPoint->GetComponentLocation();
    const FRotator Rot = FRotator::ZeroRotator;

    FActorSpawnParameters Params;
    Params.SpawnCollisionHandlingOverride =
        ESpawnActorCollisionHandlingMethod::AlwaysSpawn;

    AMyPaperMonster* Monster = GetWorld()->SpawnActor<AMyPaperMonster>(
        MonsterClass,
        Loc,
        Rot,
        Params);

    if (Monster)
    {
        // ИѓНКХЭПЁАд ХИАйАњ АЈСі АХИЎ ГбАмСм
        Monster->InitTarget(CachedPlayer, true, 800.f);
    }
}
